(modules): Добавил возможность указать каталог куда "опубликовать" результат сборки при rpmbuild

diff --git a/utils/bash_modules.d/rpmbuild b/utils/bash_modules.d/rpmbuild
--- a/utils/bash_modules.d/rpmbuild
+++ b/utils/bash_modules.d/rpmbuild
@@ -5,7 +5,9 @@
 
 . $DAAS_DATADIR/bash_modules.d/.daas-common
 
-BUILDER=
+BUILDER=''
+PUBDIR=''
+ENVOPTS=''
 
 [ -z "$DAAS_BUILD_USER" ] && DAAS_BUILD_USER='builder'
 DATADIR='/data'
@@ -13,11 +15,13 @@ DATADIR='/data'
 module_usage()
 {
     echo " "
-    echo "Usage: build builder_name [build_command | clean] [params...]"
+    echo "Usage: build container_name [-d pubdir] [build_command | clean] [params...]"
     echo "  "
     echo "builder_name  - name of builder container (in daas.yml)"
     echo "build_command - command for build in container."
     echo "clean         - remove build directory"
+    echo "Ext options:"
+    echo "-d|--directory pubdir - use pubdir for RPM directory. Default 'container_name/RPM'"
 }
 
 module_help()
@@ -60,15 +64,49 @@ prepare_build_environment()
     BUILDER_DIR=$WORKDIR/$DAAS_OUTDIR/${BUILDER}
     SOURCEDIR="$WORKDIR/$DAAS_OUTDIR/${BUILDER}/${DATADIR}"
     RPMDIR="$WORKDIR/$DAAS_OUTDIR/$BUILDER/RPM"
+    [ -n "$PUBDIR" ] && RPMDIR=$( realpath $PUBDIR )
+}
+
+
+split_options()
+{
+    PUBDIR=''
+    ENVOPTS=''
+    OTHER=''
+    [ -z "$PROG" ] && PROG="${0##*/}"
+    
+    TEMP=`getopt -n $PROG -o d:,e: -l directory:,environment: -- "$@"` || return 1
+    eval set -- "$TEMP"
+
+    while :; do
+      case "$1" in
+	  -d|--directory)
+	    shift
+	    [ "$1" == '--' ] && break
+	    PUBDIR="$1"
+	    ;;
+	  -e|--environment)
+	    shift
+	    [ "$1" == '--' ] && break
+	    ENVOPTS="${ENVOPTS} -e $1"
+	    ;;
+	  --) shift; break
+	    ;;
+      esac
+      shift
+    done
+    
+    OTHER=$@
 }
 
 run_build()
 {
     BUILD_CMD="$@"
     echo "in container '$BUILDER' run build command '$BUILD_CMD'"
-    prepare_build_environment
 
-    mkdir -p $SOURCEDIR
+    prepare_build_environment
+    
+    mkdir -p ${SOURCEDIR}
     mkdir -p ${RPMDIR}
     # чтобы пользователь под которым происходит сборка мог писать в этим каталоги
     # т.к по умолчанию они монтируются под root
@@ -81,13 +119,13 @@ run_build()
     prepare_sources "$COMMIT" "$SOURCEDIR"
     cd -
     
-    BUILD_ENV="-e DAAS_BUILD_USER=$DAAS_BUILD_USER -e DATADIR=$DATADIR -e SOURCE=$DATADIR/source.tar -e DAAS_DEBUG=$DAAS_DEBUG"
+    BUILD_ENV="-e DAAS_BUILD_USER=$DAAS_BUILD_USER -e DATADIR=$DATADIR -e SOURCE=$DATADIR/source.tar -e DAAS_DEBUG=$DAAS_DEBUG $ENVOPTS"
 
     cd $DAAS_OUTDIR/$BUILDER
        docker-compose build --force-rm || return 1
        docker-compose run $BUILD_ENV -v ${SOURCEDIR}:$DATADIR -w $DATADIR $BUILDER daas-build-helper.sh prepare || return 1
        docker-compose run --rm $BUILD_ENV -v ${SOURCEDIR}:$DATADIR -v ${RPMDIR}:/home/$DAAS_BUILD_USER/RPM -w $DATADIR/src $BUILDER $BUILD_CMD || return 1
-       # cleanup
+       # cleanup sources from container
        docker-compose run --rm -v ${SOURCEDIR}:/$DATADIR -w $DATADIR -u root $BUILDER rm -rf $DATADIR/src
        rm -rf $SOURCEDIR
        docker-compose down
@@ -98,6 +136,8 @@ run_build()
 
 cleanup_build()
 {
+   echo "Clean..."
+
    prepare_build_environment
    cd $BUILDER_DIR
    docker-compose run --rm -v ${SOURCEDIR}:/$DATADIR -v ${RPMDIR}:/home/$DAAS_BUILD_USER/RPM -w $DATADIR -u root -T $BUILDER rm -rf /home/$DAAS_BUILD_USER/RPM/ - 2>/dev/null
@@ -105,7 +145,6 @@ cleanup_build()
    cd -
    [ -n "$DAAS_OUTDIR" ] && rm -rf $DAAS_OUTDIR
 }
-
 
 [ -z "$1" ] && module_help && exit 1
 
@@ -125,6 +164,9 @@ esac
 
 BUILDER="$1"; shift
 [ -z "$BUILDER" ] && module_help && exit 1
+
+split_options $@
+eval set -- "$OTHER"
 
 case $1 in
     rpmbb)
